name: Create PDF

on:
  push:
    branches:
      - main


jobs:
  create_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          set-safe-directory: "*"
          fetch-depth: 0
          ref: main

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          git config --global --add safe.directory "$PWD" # actions/runner#2033

      - name: Create PDF
        uses: docker://lerhard/pandoc:3.1.2-3
        with:
          entrypoint: "rsc/docker/entrypoint.sh"

      - uses: actions/upload-artifact@master
        with:
          name: out
          path: out/
